//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamiLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KamiLib.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Remove Current Zone.
        /// </summary>
        internal static string Blacklist_AddRemoveZone {
            get {
                return ResourceManager.GetString("Blacklist_AddRemoveZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} Selected Areas.
        /// </summary>
        internal static string Blacklist_AddSelectedAreas {
            get {
                return ResourceManager.GetString("Blacklist_AddSelectedAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Blacklist.
        /// </summary>
        internal static string Blacklist_ClearBlacklist {
            get {
                return ResourceManager.GetString("Blacklist_ClearBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Blacklisted Areas.
        /// </summary>
        internal static string Blacklist_CurrentlyBlacklisted {
            get {
                return ResourceManager.GetString("Blacklist_CurrentlyBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blacklist is Empty.
        /// </summary>
        internal static string Blacklist_Empty {
            get {
                return ResourceManager.GetString("Blacklist_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} Selected Areas.
        /// </summary>
        internal static string Blacklist_RemoveSelectedAreas {
            get {
                return ResourceManager.GetString("Blacklist_RemoveSelectedAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search . . . .
        /// </summary>
        internal static string Blacklist_Search {
            get {
                return ResourceManager.GetString("Blacklist_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select zones to add to blacklist.
        /// </summary>
        internal static string Blacklist_SelectZones {
            get {
                return ResourceManager.GetString("Blacklist_SelectZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Search.
        /// </summary>
        internal static string Blacklist_ZoneSearch {
            get {
                return ResourceManager.GetString("Blacklist_ZoneSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing {0} Window.
        /// </summary>
        internal static string Command_ClosingWindow {
            get {
                return ResourceManager.GetString("Command_ClosingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display a list of all available sub-commands.
        /// </summary>
        internal static string Command_DisplayHelpText {
            get {
                return ResourceManager.GetString("Command_DisplayHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0} {1}&apos; does not exist..
        /// </summary>
        internal static string Command_DoesntExist {
            get {
                return ResourceManager.GetString("Command_DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0} {1} {2}&apos; does not exist..
        /// </summary>
        internal static string Command_DoesntExistExtended {
            get {
                return ResourceManager.GetString("Command_DoesntExistExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command_Label {
            get {
                return ResourceManager.GetString("Command_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration Window.
        /// </summary>
        internal static string Command_OpenConfigWindow {
            get {
                return ResourceManager.GetString("Command_OpenConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening {0} Window.
        /// </summary>
        internal static string Command_OpeningWindow {
            get {
                return ResourceManager.GetString("Command_OpeningWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0} Window.
        /// </summary>
        internal static string Command_OpenWindow {
            get {
                return ResourceManager.GetString("Command_OpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} Window cannot be opened while in a PvP area.
        /// </summary>
        internal static string Command_PvPError {
            get {
                return ResourceManager.GetString("Command_PvPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this message.
        /// </summary>
        internal static string Command_ShowThisMessage {
            get {
                return ResourceManager.GetString("Command_ShowThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Common_Remove {
            get {
                return ResourceManager.GetString("Common_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string Common_Value {
            get {
                return ResourceManager.GetString("Common_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold &apos;Shift&apos; to enable button.
        /// </summary>
        internal static string DisabledButton_HoldShift {
            get {
                return ResourceManager.GetString("DisabledButton_HoldShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item in the left pane.
        /// </summary>
        internal static string Selection_NoItemSelected {
            get {
                return ResourceManager.GetString("Selection_NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot teleport in this situation.
        /// </summary>
        internal static string Teleport_BadSituation {
            get {
                return ResourceManager.GetString("Teleport_BadSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the teleport function, you must install the &quot;Teleporter&quot; plugin.
        /// </summary>
        internal static string Teleport_InstallTeleporter {
            get {
                return ResourceManager.GetString("Teleport_InstallTeleporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string Teleport_Label {
            get {
                return ResourceManager.GetString("Teleport_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Aetheryte is not unlocked, teleport cancelled.
        /// </summary>
        internal static string Teleport_NotUnlocked {
            get {
                return ResourceManager.GetString("Teleport_NotUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporting to &apos;{0}&apos;.
        /// </summary>
        internal static string Teleport_TeleportingTo {
            get {
                return ResourceManager.GetString("Teleport_TeleportingTo", resourceCulture);
            }
        }
    }
}
