namespace KamiLib.Classes;

public enum TerritoryIntendedUseEnum {
    Town = 0,
    OpenWorld = 1,
    Inn = 2,
    Dungeon = 3,
    JailArea = 5,
    OpeningArea = 6,
    BeforeTrialDung = 7,
    AllianceRaid = 8,
    OpenWorldInstanceBattle = 9,
    Trial = 10,
    RaidPublicArea = 12,
    HousingArea = 13,
    HousingPrivateArea = 14,
    MSQPrivateArea = 15,
    Raids = 16,
    RaidFights = 17,
    ChocoboSquare = 19,
    ChocoboTutorial = 21,
    Wedding = 22,
    GoldSaucer = 23,
    DiademV1 = 26,
    BeginnerTutorial = 27,
    PvPTheFeast = 28,
    MSQEventArea = 29,
    FreeCompanyGarrison = 30,
    PalaceOfTheDead = 31,
    TreasureMapInstance = 33,
    EventTrial = 36,
    TheFeastArea = 37,
    DiademV2 = 38,
    PrivateEventArea = 40,
    Eureka = 41,
    TheFeastCrystalTower = 42,
    LeapOfFaith = 44,
    MaskedCarnival = 45,
    OceanFishing = 46,
    DiademV3 = 47,
    Bozja = 48,
}